# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc914f59ecbf236169f03606292c1bb48b8a913a4b177b123bc3195a8892790ae4e3c3ff95144ff5a94396bd6566e34251a4ab3839c621fc85f60ca661dd924d

test:
  secret_key_base: 5772f2dbf0e0a42b3e863b22df8b3caf0a3cc31865e0a5cd67c8f819306c472b2bf0b1104b88f566028111fd1a56f67166446081778b679a5dd0dad7d970e2ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
